### ISSUE TITLE
lol, self-praise smells

### ISSUE THREAD

**Issue by michaelknoch** [T1m1/htwg-scala-checkers#1]
![screen shot 2017-01-24 at 17 48 33](https://cloud.githubusercontent.com/assets/5617793/22257127/618f84a8-e25d-11e6-8771-32e6fe0ddd0f.png)

edit: und wo ist die wui?

**Comment by T1m1** [comment]
Die WUI von Steffen willst du nicht sehen ;)

**Comment by T1m1** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Buch IHK Prüfung](https://trello.com/c/l9bMMC5f/15-buch-ihk-pr%C3%BCfung)
